services:
  client-a:
    image: swatikadam16/client-a-node-app:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    secrets:
      - client_a_db
    environment:
      - NODE_ENV=dev


networks:
  app-network:
    external: true

secrets:
  client_a_db:
    external: true

